version: '2'

services:
  postgresql:
    container_name: nest_boilerplate_postgres
    image: 'postgres:latest'
    ports:
      - 5432:5432
    environment:
      POSTGRES_HOST_AUTH_METHOD: trust
      PGDATA: /data/postgres
      POSTGRES_USER: postgres
    volumes:
      - 'postgres_data:/data/postgres'
    networks:
      - app-network

  mongodb:
    container_name: nest_boilerplate_mongo
    image: mongo
    ports:
      - '27017:27017'
    environment:
      - MONGO_INITDB_ROOT_USERNAME=root
      - MONGO_INITDB_ROOT_PASSWORD=123456
    volumes:
      - 'mongodb_data:/data/db'
    networks:
      - app-network

  redis:
    container_name: nest_boilerplate_redis
    image: redis:6.2-alpine
    restart: always
    ports:
      - '6379:6379'
    command: redis-server --save 20 1 --loglevel warning --requirepass redis_123
    volumes:
      - 'redis_data:/data'
    networks:
      - app-network

  mosquitto:
    image: eclipse-mosquitto
    container_name: nest_boilerplate_mosquitto
    restart: unless-stopped
    volumes:
      - ./mosquitto:/mosquitto
      - ./mosquitto/data:/mosquitto/data
      - ./mosquitto/log:/mosquitto/log
    ports:
      - 1883:1883
      - 9002:9001
    networks:
      - app-network

  nats:
    container_name: nest_boilerplate_nats
    image: nats:latest
    ports:
      - '4222:4222' # Default NATS client port
      - '8222:8222' # Monitoring port (optional)
      - '6222:6222' # Cluster port (optional)
    command: ['-js', '--store_dir=/data'] # Enabling JetStream with data storage
    volumes:
      - nats_data:/data

  rabbitmq:
    container_name: nest_boilerplate_rabbitmq
    image: rabbitmq:3-management
    ports:
      - '5672:5672' # RabbitMQ default AMQP port
      - '15672:15672' # RabbitMQ Management UI
    environment:
      RABBITMQ_DEFAULT_USER: user
      RABBITMQ_DEFAULT_PASS: password
    volumes:
      - rabbitmq_data:/var/lib/rabbitmq

volumes:
  postgres_data:
    driver: local
  mongodb_data:
    driver: local
  redis_data:
    driver: local
  nats_data:
    driver: local
  rabbitmq_data:
    driver: local

networks:
  app-network:
    driver: bridge
